import { useState } from "react";

import { useStockHistory } from "../hooks/useStockHistory.js";
import { buildHistoricalChartModel } from "../utils/historicalChart.js";

const RANGES = ["1M", "3M", "12M", "3Y"];
const MODES = [["line", "折线", "Line"], ["bar", "柱状", "Bars"], ["candle", "K线", "K-line"]];
const ADJUSTMENTS = [["qfq", "前复权", "Forward adjusted"], ["none", "不复权", "Unadjusted"], ["hfq", "后复权", "Backward adjusted"]];

export function HistoricalStockChart({ stock, t, lang }) {
  const [range, setRange] = useState("12M"); const [mode, setMode] = useState("candle"); const [adjust, setAdjust] = useState("qfq"); const [metric, setMetric] = useState("volume");
  const { state, payload, retry } = useStockHistory({ stock, range, adjust });
  const label = (zh, en) => (lang === "zh" ? zh : en); const model = buildHistoricalChartModel({ bars: payload?.bars, mode, metric, width: 720, height: 280 });
  return <div className="historical-stock-chart"><div className="chart-toolbar decision-chart-toolbar historical-chart-toolbar"><div className="timeframe-control">{RANGES.map((item) => <button type="button" key={item} className={range === item ? "selected" : ""} onClick={() => setRange(item)}>{item}</button>)}</div><div className="chart-mode-control">{MODES.map(([key, zh, en]) => <button type="button" key={key} className={mode === key ? "selected" : ""} onClick={() => setMode(key)}>{label(zh, en)}</button>)}</div><select value={adjust} onChange={(event) => setAdjust(event.target.value)}>{ADJUSTMENTS.map(([key, zh, en]) => <option value={key} key={key}>{label(zh, en)}</option>)}</select>{mode === "bar" && <div className="chart-mode-control"><button type="button" className={metric === "volume" ? "selected" : ""} onClick={() => setMetric("volume")}>{t.volume}</button><button type="button" className={metric === "amount" ? "selected" : ""} onClick={() => setMetric("amount")}>{t.amount}</button></div>}</div><div className="price-chart kline-chart historical-chart-surface">{state === "loading" && <p>{label("正在加载真实历史行情…", "Loading verified history…")}</p>}{state === "unsupported" && <p>{label("历史图表暂仅支持 A 股。", "Historical charts currently support A-shares only.")}</p>}{state === "unavailable" && <p>{label("历史数据源暂时不可用，请重试。", "Historical data is temporarily unavailable. Please retry.")} <button type="button" onClick={retry}>{t.retry}</button></p>}{state === "error" && <p>{label("历史图表加载失败，请重试。", "Could not load historical chart. Please retry.")} <button type="button" onClick={retry}>{t.retry}</button></p>}{state === "ready" && !model.empty && <svg viewBox="0 0 720 280" preserveAspectRatio="none">{[64,118,172,226].map((y) => <line className="chart-grid-line" x1="24" x2="696" y1={y} y2={y} key={y}/>)}{mode === "line" && <polyline className="chart-line" points={model.polyline}/>} {mode === "bar" && model.columns.map((bar) => <rect key={bar.date} x={bar.x} y={bar.y} width={bar.width} height={bar.height} className={bar.rising ? "up-candle" : "down-candle"}/>)} {mode === "candle" && <><g className="chart-candles">{model.candles.map((bar) => <g key={bar.date}><line x1={bar.x} x2={bar.x} y1={bar.highY} y2={bar.lowY}/><rect x={bar.x-bar.width/2} y={Math.min(bar.openY,bar.closeY)} width={bar.width} height={Math.max(2,Math.abs(bar.openY-bar.closeY))} className={bar.rising ? "up-candle" : "down-candle"}/></g>)}</g>{model.volumeColumns.map((bar) => <rect key={bar.date} x={bar.x} y={bar.y} width={bar.width} height={bar.height} className={bar.rising ? "up-candle" : "down-candle"}/>)}</>}</svg>}</div>{payload?.warning && <p className="chart-context-note">{payload.warning}</p>}</div>;
}
