INDICATORS = [
    {
        "key": "PMI",
        "group": "Growth",
        "unit": "",
        "direction": 1,
        "weight": 0.35,
        "api_candidates": ["macro_china_pmi"],
        "keywords": ["制造业", "pmi", "PMI"],
        "fallback": 50.4,
    },
    {
        "key": "M1",
        "group": "Liquidity",
        "unit": "%",
        "direction": 1,
        "weight": 0.20,
        "api_candidates": ["macro_china_supply_of_money"],
        "keywords": ["M1", "货币"],
        "fallback": 5.8,
    },
    {
        "key": "M2",
        "group": "Liquidity",
        "unit": "%",
        "direction": 1,
        "weight": 0.25,
        "api_candidates": ["macro_china_supply_of_money", "macro_china_m2_yearly"],
        "keywords": ["M2", "准货币"],
        "fallback": 7.0,
    },
    {
        "key": "Social Financing",
        "group": "Liquidity",
        "unit": "T CNY",
        "direction": 1,
        "weight": 0.25,
        "api_candidates": ["macro_china_shrzgm"],
        "keywords": ["社会融资", "社融"],
        "fallback": 2.28,
    },
    {
        "key": "New Loans",
        "group": "Liquidity",
        "unit": "T CNY",
        "direction": 1,
        "weight": 0.15,
        "api_candidates": ["macro_rmb_loan"],
        "keywords": ["贷款", "人民币"],
        "fallback": 0.95,
    },
    {
        "key": "CPI",
        "group": "Inflation",
        "unit": "%",
        "direction": 1,
        "weight": 0.55,
        "api_candidates": ["macro_china_cpi"],
        "keywords": ["CPI", "居民消费"],
        "fallback": 0.3,
    },
    {
        "key": "PPI",
        "group": "Inflation",
        "unit": "%",
        "direction": 1,
        "weight": 0.45,
        "api_candidates": ["macro_china_ppi"],
        "keywords": ["PPI", "工业生产者"],
        "fallback": -1.4,
    },
    {
        "key": "Fixed Asset Inv.",
        "group": "Growth",
        "unit": "%",
        "direction": 1,
        "weight": 0.25,
        "api_candidates": ["macro_china_gdzctz"],
        "keywords": ["固定资产", "投资"],
        "fallback": 3.7,
    },
    {
        "key": "Home Sales Area",
        "group": "Property",
        "unit": "%",
        "direction": 1,
        "weight": 0.20,
        "api_candidates": ["macro_china_nbs_nation"],
        "keywords": ["商品房销售面积", "住宅销售面积", "房地产销售面积"],
        "fallback": -19.1,
    },
    {
        "key": "Unemployment",
        "group": "Growth",
        "unit": "%",
        "direction": -1,
        "weight": 0.20,
        "api_candidates": ["macro_china_urban_unemployment"],
        "keywords": ["失业率", "调查失业"],
        "fallback": 5.0,
    },
    {
        "key": "FX Reserves",
        "group": "External",
        "unit": "T USD",
        "direction": 1,
        "weight": 0.45,
        "api_candidates": ["macro_china_fx_reserves_yearly"],
        "keywords": ["外汇储备"],
        "fallback": 3.23,
    },
    {
        "key": "CN 10Y Yield",
        "group": "Rates",
        "unit": "%",
        "direction": -1,
        "weight": 0.15,
        "api_candidates": ["bond_china_yield"],
        "keywords": ["10年", "10Y", "十年"],
        "fallback": 1.72,
    },
    {
        "key": "USD/CNY",
        "group": "External",
        "unit": "",
        "direction": -1,
        "weight": 0.55,
        "api_candidates": ["currency_history", "fx_pair_quote"],
        "keywords": ["USD/CNY", "美元", "人民币"],
        "fallback": 7.18,
    },
]
